<?php 


// function to create the DB / Options / Defaults					
function ss_earthquake_form_install() {
   	global $wpdb;
   	$db_name = $wpdb->dbname;
  	$table_name = $wpdb->prefix . 'ss_earthquake_form';
  	$table_name2 = $wpdb->prefix . 'ss_province';
	// create the ECPT metabox database table
	if($wpdb->get_var("show tables like '$table_name'") != $table_name) 
	{
		$sql = "CREATE TABLE IF NOT EXISTS $table_name (
				  `id` int(5) zerofill NOT NULL AUTO_INCREMENT,
				  `agent_id` int(5) zerofill NOT NULL,
				  `agent_name` varchar(256) NOT NULL,
				  `registration_num` varchar(256) NOT NULL,
				  `province` text COLLATE utf8_turkish_ci NOT NULL,
		  		  `city` text COLLATE utf8_turkish_ci NOT NULL,
				  `address` text NOT NULL,
				  `phone` varchar(256) NOT NULL,
				  `email` varchar(50) NOT NULL,
				  `contact_person` varchar(256) NOT NULL,
				  `competent_person_cell` varchar(256) NOT NULL,
				  `signage` tinyint(1) NOT NULL,
				  `signage_reason` text NOT NULL,
				  PRIMARY KEY (`id`) 
				) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci AUTO_INCREMENT=1024; ALTER DATABASE $db_name COLLATE utf8_turkish_ci;";

		require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
		dbDelta($sql);
	}


	if($wpdb->get_var("show tables like '$table_name2'") != $table_name2) 
	{
		$sql = "CREATE TABLE IF NOT EXISTS $table_name2 (
		  `id` int(11) NOT NULL AUTO_INCREMENT,
		  `province` text COLLATE utf8_turkish_ci NOT NULL,
		  `city` text COLLATE utf8_turkish_ci NOT NULL,
		  PRIMARY KEY (`id`)
		) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci AUTO_INCREMENT=1024 ;

--
-- Dumping data for table `wp_provinces`
--

INSERT INTO `wp_ss_province` (`id`, `province`, `city`) VALUES
(1, 'Adana', 'Seyhan'),
(2, 'Adana', 'Ceyhan'),
(3, 'Adana', 'Feke'),
(4, 'Adana', 'Karaisalı'),
(5, 'Adana', 'Karataş'),
(6, 'Adana', 'Kozan'),
(7, 'Adana', 'Pozantı'),
(8, 'Adana', 'Saimbeyli'),
(9, 'Adana', 'Tufanbeyli'),
(10, 'Adana', 'Yumurtalık'),
(11, 'Adana', 'Yüreğir'),
(12, 'Adana', 'Aladağ'),
(13, 'Adana', 'İmamoğlu'),
(14, 'Adana', 'Sarıçam'),
(15, 'Adana', 'Çukurova'),
(16, 'Adıyaman', 'Adıyaman Merkez'),
(17, 'Adıyaman', 'Besni'),
(18, 'Adıyaman', 'Çelikhan'),
(19, 'Adıyaman', 'Gerger'),
(20, 'Adıyaman', 'Gölbaşı / Adıyaman'),
(21, 'Adıyaman', 'Kahta'),
(22, 'Adıyaman', 'Samsat'),
(23, 'Adıyaman', 'Sincik'),
(24, 'Adıyaman', 'Tut'),
(25, 'Afyonkarahisar', 'Afyonkarahisar Merkez'),
(26, 'Afyonkarahisar', 'Bolvadin'),
(27, 'Afyonkarahisar', 'Çay'),
(28, 'Afyonkarahisar', 'Dazkırı'),
(29, 'Afyonkarahisar', 'Dinar'),
(30, 'Afyonkarahisar', 'Emirdağ'),
(31, 'Afyonkarahisar', 'İhsaniye'),
(32, 'Afyonkarahisar', 'Sandıklı'),
(33, 'Afyonkarahisar', 'Sinanpaşa'),
(34, 'Afyonkarahisar', 'Sultandağı'),
(35, 'Afyonkarahisar', 'Şuhut'),
(36, 'Afyonkarahisar', 'Başmakçı'),
(37, 'Afyonkarahisar', 'Bayat / Afyonkarahisar'),
(38, 'Afyonkarahisar', 'İscehisar'),
(39, 'Afyonkarahisar', 'Çobanlar'),
(40, 'Afyonkarahisar', 'Evciler'),
(41, 'Afyonkarahisar', 'Hocalar'),
(42, 'Afyonkarahisar', 'Kızılören'),
(43, 'Ağrı', 'Ağrı Merkez'),
(44, 'Ağrı', 'Diyadin'),
(45, 'Ağrı', 'Doğubayazıt'),
(46, 'Ağrı', 'Eleşkirt'),
(47, 'Ağrı', 'Hamur'),
(48, 'Ağrı', 'Patnos'),
(49, 'Ağrı', 'Taşlıçay'),
(50, 'Ağrı', 'Tutak'),
(51, 'Aksaray', 'Aksaray Merkez'),
(52, 'Aksaray', 'Ortaköy / Aksaray'),
(53, 'Aksaray', 'Ağaçören'),
(54, 'Aksaray', 'Güzelyurt'),
(55, 'Aksaray', 'Sarıyahşi'),
(56, 'Aksaray', 'Eskil'),
(57, 'Aksaray', 'Gülağaç'),
(58, 'Amasya', 'Amasya Merkez'),
(59, 'Amasya', 'Göynücek'),
(60, 'Amasya', 'Gümüşhacıköy'),
(61, 'Amasya', 'Merzifon'),
(62, 'Amasya', 'Suluova'),
(63, 'Amasya', 'Taşova'),
(64, 'Amasya', 'Hamamözü'),
(65, 'Ankara', 'Altındağ'),
(66, 'Ankara', 'Ayaş'),
(67, 'Ankara', 'Bala'),
(68, 'Ankara', 'Beypazarı'),
(69, 'Ankara', 'Çamlıdere'),
(70, 'Ankara', 'Çankaya'),
(71, 'Ankara', 'Çubuk'),
(72, 'Ankara', 'Elmadağ'),
(73, 'Ankara', 'Güdül'),
(74, 'Ankara', 'Haymana'),
(75, 'Ankara', 'Kalecik'),
(76, 'Ankara', 'Kızılcahamam'),
(77, 'Ankara', 'Nallıhan'),
(78, 'Ankara', 'Polatlı'),
(79, 'Ankara', 'Şereflikoçhisar'),
(80, 'Ankara', 'Yenimahalle'),
(81, 'Ankara', 'Gölbaşı / Ankara'),
(82, 'Ankara', 'Keçiören'),
(83, 'Ankara', 'Mamak'),
(84, 'Ankara', 'Sincan'),
(85, 'Ankara', 'Kazan'),
(86, 'Ankara', 'Akyurt'),
(87, 'Ankara', 'Etimesgut'),
(88, 'Ankara', 'Evren'),
(89, 'Ankara', 'Pursaklar'),
(90, 'Antalya', 'Akseki'),
(91, 'Antalya', 'Alanya'),
(92, 'Antalya', 'Elmalı'),
(93, 'Antalya', 'Finike'),
(94, 'Antalya', 'Gazipaşa'),
(95, 'Antalya', 'Gündoğmuş'),
(96, 'Antalya', 'Kaş'),
(97, 'Antalya', 'Korkuteli'),
(98, 'Antalya', 'Kumluca'),
(99, 'Antalya', 'Manavgat'),
(100, 'Antalya', 'Serik'),
(101, 'Antalya', 'Demre'),
(102, 'Antalya', 'İbradı'),
(103, 'Antalya', 'Kemer / Antalya'),
(104, 'Antalya', 'Aksu / Antalya'),
(105, 'Antalya', 'Döşemealtı'),
(106, 'Antalya', 'Kepez'),
(107, 'Antalya', 'Konyaaltı'),
(108, 'Antalya', 'Muratpaşa'),
(109, 'Ardahan', 'Ardahan Merkez'),
(110, 'Ardahan', 'Çıldır'),
(111, 'Ardahan', 'Göle'),
(112, 'Ardahan', 'Hanak'),
(113, 'Ardahan', 'Posof'),
(114, 'Ardahan', 'Damal'),
(115, 'Artvin', 'Ardanuç'),
(116, 'Artvin', 'Arhavi'),
(117, 'Artvin', 'Artvin Merkez'),
(118, 'Artvin', 'Borçka'),
(119, 'Artvin', 'Hopa'),
(120, 'Artvin', 'Şavşat'),
(121, 'Artvin', 'Yusufeli'),
(122, 'Artvin', 'Murgul'),
(123, 'Aydın', 'Bozdoğan'),
(124, 'Aydın', 'Çine'),
(125, 'Aydın', 'Germencik'),
(126, 'Aydın', 'Karacasu'),
(127, 'Aydın', 'Koçarlı'),
(128, 'Aydın', 'Kuşadası'),
(129, 'Aydın', 'Kuyucak'),
(130, 'Aydın', 'Nazilli'),
(131, 'Aydın', 'Söke'),
(132, 'Aydın', 'Sultanhisar'),
(133, 'Aydın', 'Yenipazar / Aydın'),
(134, 'Aydın', 'Buharkent'),
(135, 'Aydın', 'İncirliova'),
(136, 'Aydın', 'Karpuzlu'),
(137, 'Aydın', 'Köşk'),
(138, 'Aydın', 'Didim'),
(139, 'Aydın', 'Efeler'),
(140, 'Balıkesir', 'Ayvalık'),
(141, 'Balıkesir', 'Balya'),
(142, 'Balıkesir', 'Bandırma'),
(143, 'Balıkesir', 'Bigadiç'),
(144, 'Balıkesir', 'Burhaniye'),
(145, 'Balıkesir', 'Dursunbey'),
(146, 'Balıkesir', 'Edremit / Balıkesir'),
(147, 'Balıkesir', 'Erdek'),
(148, 'Balıkesir', 'Gönen / Balıkesir'),
(149, 'Balıkesir', 'Havran'),
(150, 'Balıkesir', 'İvrindi'),
(151, 'Balıkesir', 'Kepsut'),
(152, 'Balıkesir', 'Manyas'),
(153, 'Balıkesir', 'Savaştepe'),
(154, 'Balıkesir', 'Sındırgı'),
(155, 'Balıkesir', 'Susurluk'),
(156, 'Balıkesir', 'Marmara'),
(157, 'Balıkesir', 'Gömeç'),
(158, 'Balıkesir', 'Altıeylül'),
(159, 'Balıkesir', 'Karesi'),
(160, 'Bartın', 'Bartın Merkez'),
(161, 'Bartın', 'Kurucaşile'),
(162, 'Bartın', 'Ulus'),
(163, 'Bartın', 'Amasra'),
(164, 'Batman', 'Batman Merkez'),
(165, 'Batman', 'Beşiri'),
(166, 'Batman', 'Gercüş'),
(167, 'Batman', 'Kozluk'),
(168, 'Batman', 'Sason'),
(169, 'Batman', 'Hasankeyf'),
(170, 'Bayburt', 'Bayburt Merkez'),
(171, 'Bayburt', 'Aydıntepe'),
(172, 'Bayburt', 'Demirözü'),
(173, 'Bilecik', 'Bilecik Merkez'),
(174, 'Bilecik', 'Bozüyük'),
(175, 'Bilecik', 'Gölpazarı'),
(176, 'Bilecik', 'Osmaneli'),
(177, 'Bilecik', 'Pazaryeri'),
(178, 'Bilecik', 'Söğüt'),
(179, 'Bilecik', 'Yenipazar / Bilecik'),
(180, 'Bilecik', 'İnhisar'),
(181, 'Bingöl', 'Bingöl Merkez'),
(182, 'Bingöl', 'Genç'),
(183, 'Bingöl', 'Karlıova'),
(184, 'Bingöl', 'Kiğı'),
(185, 'Bingöl', 'Solhan'),
(186, 'Bingöl', 'Adaklı'),
(187, 'Bingöl', 'Yayladere'),
(188, 'Bingöl', 'Yedisu'),
(189, 'Bitlis', 'Adilcevaz'),
(190, 'Bitlis', 'Ahlat'),
(191, 'Bitlis', 'Bitlis Merkez'),
(192, 'Bitlis', 'Hizan'),
(193, 'Bitlis', 'Mutki'),
(194, 'Bitlis', 'Tatvan'),
(195, 'Bitlis', 'Güroymak'),
(196, 'Bolu', 'Bolu Merkez'),
(197, 'Bolu', 'Gerede'),
(198, 'Bolu', 'Göynük'),
(199, 'Bolu', 'Kıbrıscık'),
(200, 'Bolu', 'Mengen'),
(201, 'Bolu', 'Mudurnu'),
(202, 'Bolu', 'Seben'),
(203, 'Bolu', 'Dörtdivan'),
(204, 'Bolu', 'Yeniçağa'),
(205, 'Burdur', 'Ağlasun'),
(206, 'Burdur', 'Bucak'),
(207, 'Burdur', 'Burdur Merkez'),
(208, 'Burdur', 'Gölhisar'),
(209, 'Burdur', 'Tefenni'),
(210, 'Burdur', 'Yeşilova'),
(211, 'Burdur', 'Karamanlı'),
(212, 'Burdur', 'Kemer / Burdur'),
(213, 'Burdur', 'Altınyayla / Burdur'),
(214, 'Burdur', 'Çavdır'),
(215, 'Burdur', 'Çeltikçi'),
(216, 'Bursa', 'Gemlik'),
(217, 'Bursa', 'İnegöl'),
(218, 'Bursa', 'İznik'),
(219, 'Bursa', 'Karacabey'),
(220, 'Bursa', 'Keles'),
(221, 'Bursa', 'Mudanya'),
(222, 'Bursa', 'Mustafakemalpaşa'),
(223, 'Bursa', 'Orhaneli'),
(224, 'Bursa', 'Orhangazi'),
(225, 'Bursa', 'Yenişehir / Bursa'),
(226, 'Bursa', 'Büyükorhan'),
(227, 'Bursa', 'Harmancık'),
(228, 'Bursa', 'Nilüfer'),
(229, 'Bursa', 'Osmangazi'),
(230, 'Bursa', 'Yıldırım'),
(231, 'Bursa', 'Gürsu'),
(232, 'Bursa', 'Kestel'),
(233, 'Çanakkale', 'Ayvacık / Çanakkale'),
(234, 'Çanakkale', 'Bayramiç'),
(235, 'Çanakkale', 'Biga'),
(236, 'Çanakkale', 'Bozcaada'),
(237, 'Çanakkale', 'Çan'),
(238, 'Çanakkale', 'Çanakkale Merkez'),
(239, 'Çanakkale', 'Eceabat'),
(240, 'Çanakkale', 'Ezine'),
(241, 'Çanakkale', 'Gelibolu'),
(242, 'Çanakkale', 'Gökçeada'),
(243, 'Çanakkale', 'Lapseki'),
(244, 'Çanakkale', 'Yenice / Çanakkale'),
(245, 'Çankırı', 'Çankırı Merkez'),
(246, 'Çankırı', 'Çerkeş'),
(247, 'Çankırı', 'Eldivan'),
(248, 'Çankırı', 'Ilgaz'),
(249, 'Çankırı', 'Kurşunlu'),
(250, 'Çankırı', 'Orta'),
(251, 'Çankırı', 'Şabanözü'),
(252, 'Çankırı', 'Yapraklı'),
(253, 'Çankırı', 'Atkaracalar'),
(254, 'Çankırı', 'Kızılırmak'),
(255, 'Çankırı', 'Bayramören'),
(256, 'Çankırı', 'Korgun'),
(257, 'Çorum', 'Alaca'),
(258, 'Çorum', 'Bayat / Çorum'),
(259, 'Çorum', 'Çorum Merkez'),
(260, 'Çorum', 'İskilip'),
(261, 'Çorum', 'Kargı'),
(262, 'Çorum', 'Mecitözü'),
(263, 'Çorum', 'Ortaköy / Çorum'),
(264, 'Çorum', 'Osmancık'),
(265, 'Çorum', 'Sungurlu'),
(266, 'Çorum', 'Boğazkale'),
(267, 'Çorum', 'Uğurludağ'),
(268, 'Çorum', 'Dodurga'),
(269, 'Çorum', 'Laçin'),
(270, 'Çorum', 'Oğuzlar'),
(271, 'Denizli', 'Acıpayam'),
(272, 'Denizli', 'Buldan'),
(273, 'Denizli', 'Çal'),
(274, 'Denizli', 'Çameli'),
(275, 'Denizli', 'Çardak'),
(276, 'Denizli', 'Çivril'),
(277, 'Denizli', 'Güney'),
(278, 'Denizli', 'Kale / Denizli'),
(279, 'Denizli', 'Sarayköy'),
(280, 'Denizli', 'Tavas'),
(281, 'Denizli', 'Babadağ'),
(282, 'Denizli', 'Bekilli'),
(283, 'Denizli', 'Honaz'),
(284, 'Denizli', 'Serinhisar'),
(285, 'Denizli', 'Pamukkale'),
(286, 'Denizli', 'Baklan'),
(287, 'Denizli', 'Beyağaç'),
(288, 'Denizli', 'Bozkurt / Denizli'),
(289, 'Denizli', 'Merkezefendi'),
(290, 'Diyarbakır', 'Bismil'),
(291, 'Diyarbakır', 'Çermik'),
(292, 'Diyarbakır', 'Çınar'),
(293, 'Diyarbakır', 'Çüngüş'),
(294, 'Diyarbakır', 'Dicle'),
(295, 'Diyarbakır', 'Ergani'),
(296, 'Diyarbakır', 'Hani'),
(297, 'Diyarbakır', 'Hazro'),
(298, 'Diyarbakır', 'Kulp'),
(299, 'Diyarbakır', 'Lice'),
(300, 'Diyarbakır', 'Silvan'),
(301, 'Diyarbakır', 'Eğil'),
(302, 'Diyarbakır', 'Kocaköy'),
(303, 'Diyarbakır', 'Bağlar'),
(304, 'Diyarbakır', 'Kayapınar'),
(305, 'Diyarbakır', 'Sur'),
(306, 'Diyarbakır', 'Yenişehir / Diyarbakır'),
(307, 'Düzce', 'Akçakoca'),
(308, 'Düzce', 'Düzce Merkez'),
(309, 'Düzce', 'Yığılca'),
(310, 'Düzce', 'Cumayeri'),
(311, 'Düzce', 'Gölyaka'),
(312, 'Düzce', 'Çilimli'),
(313, 'Düzce', 'Gümüşova'),
(314, 'Düzce', 'Kaynaşlı'),
(315, 'Edirne', 'Edirne Merkez'),
(316, 'Edirne', 'Enez'),
(317, 'Edirne', 'Havsa'),
(318, 'Edirne', 'İpsala'),
(319, 'Edirne', 'Keşan'),
(320, 'Edirne', 'Lalapaşa'),
(321, 'Edirne', 'Meriç'),
(322, 'Edirne', 'Uzunköprü'),
(323, 'Edirne', 'Süloğlu'),
(324, 'Elazığ', 'Ağın'),
(325, 'Elazığ', 'Baskil'),
(326, 'Elazığ', 'Elazığ Merkez'),
(327, 'Elazığ', 'Karakoçan'),
(328, 'Elazığ', 'Keban'),
(329, 'Elazığ', 'Maden'),
(330, 'Elazığ', 'Palu'),
(331, 'Elazığ', 'Sivrice'),
(332, 'Elazığ', 'Arıcak'),
(333, 'Elazığ', 'Kovancılar'),
(334, 'Elazığ', 'Alacakaya'),
(335, 'Erzincan', 'Çayırlı'),
(336, 'Erzincan', 'Erzincan Merkez'),
(337, 'Erzincan', 'İliç'),
(338, 'Erzincan', 'Kemah'),
(339, 'Erzincan', 'Kemaliye'),
(340, 'Erzincan', 'Refahiye'),
(341, 'Erzincan', 'Tercan'),
(342, 'Erzincan', 'Üzümlü'),
(343, 'Erzincan', 'Otlukbeli'),
(344, 'Erzurum', 'Aşkale'),
(345, 'Erzurum', 'Çat'),
(346, 'Erzurum', 'Hınıs'),
(347, 'Erzurum', 'Horasan'),
(348, 'Erzurum', 'İspir'),
(349, 'Erzurum', 'Karayazı'),
(350, 'Erzurum', 'Narman'),
(351, 'Erzurum', 'Oltu'),
(352, 'Erzurum', 'Olur'),
(353, 'Erzurum', 'Pasinler'),
(354, 'Erzurum', 'Şenkaya'),
(355, 'Erzurum', 'Tekman'),
(356, 'Erzurum', 'Tortum'),
(357, 'Erzurum', 'Karaçoban'),
(358, 'Erzurum', 'Uzundere'),
(359, 'Erzurum', 'Pazaryolu'),
(360, 'Erzurum', 'Aziziye'),
(361, 'Erzurum', 'Köprüköy'),
(362, 'Erzurum', 'Palandöken'),
(363, 'Erzurum', 'Yakutiye'),
(364, 'Eskişehir', 'Çifteler'),
(365, 'Eskişehir', 'Mahmudiye'),
(366, 'Eskişehir', 'Mihalıççık'),
(367, 'Eskişehir', 'Sarıcakaya'),
(368, 'Eskişehir', 'Seyitgazi'),
(369, 'Eskişehir', 'Sivrihisar'),
(370, 'Eskişehir', 'Alpu'),
(371, 'Eskişehir', 'Beylikova'),
(372, 'Eskişehir', 'İnönü'),
(373, 'Eskişehir', 'Günyüzü'),
(374, 'Eskişehir', 'Han'),
(375, 'Eskişehir', 'Mihalgazi'),
(376, 'Eskişehir', 'Odunpazarı'),
(377, 'Eskişehir', 'Tepebaşı'),
(378, 'Gaziantep', 'Araban'),
(379, 'Gaziantep', 'İslahiye'),
(380, 'Gaziantep', 'Nizip'),
(381, 'Gaziantep', 'Oğuzeli'),
(382, 'Gaziantep', 'Yavuzeli'),
(383, 'Gaziantep', 'Şahinbey'),
(384, 'Gaziantep', 'Şehitkamil'),
(385, 'Gaziantep', 'Karkamış'),
(386, 'Gaziantep', 'Nurdağı'),
(387, 'Giresun', 'Alucra'),
(388, 'Giresun', 'Bulancak'),
(389, 'Giresun', 'Dereli'),
(390, 'Giresun', 'Espiye'),
(391, 'Giresun', 'Eynesil'),
(392, 'Giresun', 'Giresun Merkez'),
(393, 'Giresun', 'Görele'),
(394, 'Giresun', 'Keşap'),
(395, 'Giresun', 'Şebinkarahisar'),
(396, 'Giresun', 'Tirebolu'),
(397, 'Giresun', 'Piraziz'),
(398, 'Giresun', 'Yağlıdere'),
(399, 'Giresun', 'Çamoluk'),
(400, 'Giresun', 'Çanakçı'),
(401, 'Giresun', 'Doğankent'),
(402, 'Giresun', 'Güce'),
(403, 'Gümüşhane', 'Gümüşhane Merkez'),
(404, 'Gümüşhane', 'Kelkit'),
(405, 'Gümüşhane', 'Şiran'),
(406, 'Gümüşhane', 'Torul'),
(407, 'Gümüşhane', 'Köse'),
(408, 'Gümüşhane', 'Kürtün'),
(409, 'Hakkari', 'Çukurca'),
(410, 'Hakkari', 'Hakkari Merkez'),
(411, 'Hakkari', 'Şemdinli'),
(412, 'Hakkari', 'Yüksekova'),
(413, 'Hatay', 'Altınözü'),
(414, 'Hatay', 'Dörtyol'),
(415, 'Hatay', 'Hassa'),
(416, 'Hatay', 'İskenderun'),
(417, 'Hatay', 'Kırıkhan'),
(418, 'Hatay', 'Reyhanlı'),
(419, 'Hatay', 'Samandağ'),
(420, 'Hatay', 'Yayladağı'),
(421, 'Hatay', 'Erzin'),
(422, 'Hatay', 'Belen'),
(423, 'Hatay', 'Kumlu'),
(424, 'Hatay', 'Antakya'),
(425, 'Hatay', 'Arsuz'),
(426, 'Hatay', 'Defne'),
(427, 'Hatay', 'Payas'),
(428, 'Iğdır', 'Aralık'),
(429, 'Iğdır', 'Iğdır Merkez'),
(430, 'Iğdır', 'Tuzluca'),
(431, 'Iğdır', 'Karakoyunlu'),
(432, 'Isparta', 'Atabey'),
(433, 'Isparta', 'Eğirdir'),
(434, 'Isparta', 'Gelendost'),
(435, 'Isparta', 'Isparta Merkez'),
(436, 'Isparta', 'Keçiborlu'),
(437, 'Isparta', 'Senirkent'),
(438, 'Isparta', 'Sütçüler'),
(439, 'Isparta', 'Şarkikaraağaç'),
(440, 'Isparta', 'Uluborlu'),
(441, 'Isparta', 'Yalvaç'),
(442, 'Isparta', 'Aksu / Isparta'),
(443, 'Isparta', 'Gönen / Isparta'),
(444, 'Isparta', 'Yenişarbademli'),
(445, 'İstanbul', 'Adalar'),
(446, 'İstanbul', 'Bakırköy'),
(447, 'İstanbul', 'Beşiktaş'),
(448, 'İstanbul', 'Beykoz'),
(449, 'İstanbul', 'Beyoğlu'),
(450, 'İstanbul', 'Çatalca'),
(451, 'İstanbul', 'Eyüp'),
(452, 'İstanbul', 'Fatih'),
(453, 'İstanbul', 'Gaziosmanpaşa'),
(454, 'İstanbul', 'Kadıköy'),
(455, 'İstanbul', 'Kartal'),
(456, 'İstanbul', 'Sarıyer'),
(457, 'İstanbul', 'Silivri'),
(458, 'İstanbul', 'Şile'),
(459, 'İstanbul', 'Şişli'),
(460, 'İstanbul', 'Üsküdar'),
(461, 'İstanbul', 'Zeytinburnu'),
(462, 'İstanbul', 'Büyükçekmece'),
(463, 'İstanbul', 'Kağıthane'),
(464, 'İstanbul', 'Küçükçekmece'),
(465, 'İstanbul', 'Pendik'),
(466, 'İstanbul', 'Ümraniye'),
(467, 'İstanbul', 'Bayrampaşa'),
(468, 'İstanbul', 'Avcılar'),
(469, 'İstanbul', 'Bağcılar'),
(470, 'İstanbul', 'Bahçelievler'),
(471, 'İstanbul', 'Güngören'),
(472, 'İstanbul', 'Maltepe'),
(473, 'İstanbul', 'Sultanbeyli'),
(474, 'İstanbul', 'Tuzla'),
(475, 'İstanbul', 'Esenler'),
(476, 'İstanbul', 'Arnavutköy'),
(477, 'İstanbul', 'Ataşehir'),
(478, 'İstanbul', 'Başakşehir'),
(479, 'İstanbul', 'Beylikdüzü'),
(480, 'İstanbul', 'Çekmeköy'),
(481, 'İstanbul', 'Esenyurt'),
(482, 'İstanbul', 'Sancaktepe'),
(483, 'İstanbul', 'Sultangazi'),
(484, 'İzmir', 'Aliağa'),
(485, 'İzmir', 'Bayındır'),
(486, 'İzmir', 'Bergama'),
(487, 'İzmir', 'Bornova'),
(488, 'İzmir', 'Çeşme'),
(489, 'İzmir', 'Dikili'),
(490, 'İzmir', 'Foça'),
(491, 'İzmir', 'Karaburun'),
(492, 'İzmir', 'Karşıyaka'),
(493, 'İzmir', 'Kemalpaşa'),
(494, 'İzmir', 'Kınık'),
(495, 'İzmir', 'Kiraz'),
(496, 'İzmir', 'Menemen'),
(497, 'İzmir', 'Ödemiş'),
(498, 'İzmir', 'Seferihisar'),
(499, 'İzmir', 'Selçuk'),
(500, 'İzmir', 'Tire'),
(501, 'İzmir', 'Torbalı'),
(502, 'İzmir', 'Urla'),
(503, 'İzmir', 'Beydağ'),
(504, 'İzmir', 'Buca'),
(505, 'İzmir', 'Konak'),
(506, 'İzmir', 'Menderes'),
(507, 'İzmir', 'Balçova'),
(508, 'İzmir', 'Çiğli'),
(509, 'İzmir', 'Gaziemir'),
(510, 'İzmir', 'Narlıdere'),
(511, 'İzmir', 'Güzelbahçe'),
(512, 'İzmir', 'Bayraklı'),
(513, 'İzmir', 'Karabağlar'),
(514, 'Kahramanmaraş', 'Afşin'),
(515, 'Kahramanmaraş', 'Andırın'),
(516, 'Kahramanmaraş', 'Elbistan'),
(517, 'Kahramanmaraş', 'Göksun'),
(518, 'Kahramanmaraş', 'Pazarcık'),
(519, 'Kahramanmaraş', 'Türkoğlu'),
(520, 'Kahramanmaraş', 'Çağlayancerit'),
(521, 'Kahramanmaraş', 'Ekinözü'),
(522, 'Kahramanmaraş', 'Nurhak'),
(523, 'Kahramanmaraş', 'Dulkadiroğlu'),
(524, 'Kahramanmaraş', 'Onikişubat'),
(525, 'Karabük', 'Eflani'),
(526, 'Karabük', 'Eskipazar'),
(527, 'Karabük', 'Karabük Merkez'),
(528, 'Karabük', 'Ovacık / Karabük'),
(529, 'Karabük', 'Safranbolu'),
(530, 'Karabük', 'Yenice / Karabük'),
(531, 'Karaman', 'Ermenek'),
(532, 'Karaman', 'Karaman Merkez'),
(533, 'Karaman', 'Ayrancı'),
(534, 'Karaman', 'Kazımkarabekir'),
(535, 'Karaman', 'Başyayla'),
(536, 'Karaman', 'Sarıveliler'),
(537, 'Kars', 'Arpaçay'),
(538, 'Kars', 'Digor'),
(539, 'Kars', 'Kağızman'),
(540, 'Kars', 'Kars Merkez'),
(541, 'Kars', 'Sarıkamış'),
(542, 'Kars', 'Selim'),
(543, 'Kars', 'Susuz'),
(544, 'Kars', 'Akyaka'),
(545, 'Kastamonu', 'Abana'),
(546, 'Kastamonu', 'Araç'),
(547, 'Kastamonu', 'Azdavay'),
(548, 'Kastamonu', 'Bozkurt / Kastamonu'),
(549, 'Kastamonu', 'Cide'),
(550, 'Kastamonu', 'Çatalzeytin'),
(551, 'Kastamonu', 'Daday'),
(552, 'Kastamonu', 'Devrekani'),
(553, 'Kastamonu', 'İnebolu'),
(554, 'Kastamonu', 'Kastamonu Merkez'),
(555, 'Kastamonu', 'Küre'),
(556, 'Kastamonu', 'Taşköprü'),
(557, 'Kastamonu', 'Tosya'),
(558, 'Kastamonu', 'İhsangazi'),
(559, 'Kastamonu', 'Pınarbaşı / Kastamonu'),
(560, 'Kastamonu', 'Şenpazar'),
(561, 'Kastamonu', 'Ağlı'),
(562, 'Kastamonu', 'Doğanyurt'),
(563, 'Kastamonu', 'Hanönü'),
(564, 'Kastamonu', 'Seydiler'),
(565, 'Kayseri', 'Bünyan'),
(566, 'Kayseri', 'Develi'),
(567, 'Kayseri', 'Felahiye'),
(568, 'Kayseri', 'İncesu'),
(569, 'Kayseri', 'Pınarbaşı / Kayseri'),
(570, 'Kayseri', 'Sarıoğlan'),
(571, 'Kayseri', 'Sarız'),
(572, 'Kayseri', 'Tomarza'),
(573, 'Kayseri', 'Yahyalı'),
(574, 'Kayseri', 'Yeşilhisar'),
(575, 'Kayseri', 'Akkışla'),
(576, 'Kayseri', 'Talas'),
(577, 'Kayseri', 'Kocasinan'),
(578, 'Kayseri', 'Melikgazi'),
(579, 'Kayseri', 'Hacılar'),
(580, 'Kayseri', 'Özvatan'),
(581, 'Kırıkkale', 'Delice'),
(582, 'Kırıkkale', 'Keskin'),
(583, 'Kırıkkale', 'Kırıkkale Merkez'),
(584, 'Kırıkkale', 'Sulakyurt'),
(585, 'Kırıkkale', 'Bahşili'),
(586, 'Kırıkkale', 'Balışeyh'),
(587, 'Kırıkkale', 'Çelebi'),
(588, 'Kırıkkale', 'Karakeçili'),
(589, 'Kırıkkale', 'Yahşihan'),
(590, 'Kırklareli', 'Babaeski'),
(591, 'Kırklareli', 'Demirköy'),
(592, 'Kırklareli', 'Kırklareli Merkez'),
(593, 'Kırklareli', 'Kofçaz'),
(594, 'Kırklareli', 'Lüleburgaz'),
(595, 'Kırklareli', 'Pehlivanköy'),
(596, 'Kırklareli', 'Pınarhisar'),
(597, 'Kırklareli', 'Vize'),
(598, 'Kırşehir', 'Çiçekdağı'),
(599, 'Kırşehir', 'Kaman'),
(600, 'Kırşehir', 'Kırşehir Merkez'),
(601, 'Kırşehir', 'Mucur'),
(602, 'Kırşehir', 'Akpınar'),
(603, 'Kırşehir', 'Akçakent'),
(604, 'Kırşehir', 'Boztepe'),
(605, 'Kilis', 'Kilis Merkez'),
(606, 'Kilis', 'Elbeyli'),
(607, 'Kilis', 'Musabeyli'),
(608, 'Kilis', 'Polateli'),
(609, 'Kocaeli', 'Gebze'),
(610, 'Kocaeli', 'Gölcük'),
(611, 'Kocaeli', 'Kandıra'),
(612, 'Kocaeli', 'Karamürsel'),
(613, 'Kocaeli', 'Körfez'),
(614, 'Kocaeli', 'Derince'),
(615, 'Kocaeli', 'Başiskele'),
(616, 'Kocaeli', 'Çayırova'),
(617, 'Kocaeli', 'Darıca'),
(618, 'Kocaeli', 'Dilovası'),
(619, 'Kocaeli', 'İzmit'),
(620, 'Kocaeli', 'Kartepe'),
(621, 'Konya', 'Akşehir'),
(622, 'Konya', 'Beyşehir'),
(623, 'Konya', 'Bozkır'),
(624, 'Konya', 'Cihanbeyli'),
(625, 'Konya', 'Çumra'),
(626, 'Konya', 'Doğanhisar'),
(627, 'Konya', 'Ereğli / Konya'),
(628, 'Konya', 'Hadim'),
(629, 'Konya', 'Ilgın'),
(630, 'Konya', 'Kadınhanı'),
(631, 'Konya', 'Karapınar'),
(632, 'Konya', 'Kulu'),
(633, 'Konya', 'Sarayönü'),
(634, 'Konya', 'Seydişehir'),
(635, 'Konya', 'Yunak'),
(636, 'Konya', 'Akören'),
(637, 'Konya', 'Altınekin'),
(638, 'Konya', 'Derebucak'),
(639, 'Konya', 'Hüyük'),
(640, 'Konya', 'Karatay'),
(641, 'Konya', 'Meram'),
(642, 'Konya', 'Selçuklu'),
(643, 'Konya', 'Taşkent'),
(644, 'Konya', 'Ahırlı'),
(645, 'Konya', 'Çeltik'),
(646, 'Konya', 'Derbent'),
(647, 'Konya', 'Emirgazi'),
(648, 'Konya', 'Güneysınır'),
(649, 'Konya', 'Halkapınar'),
(650, 'Konya', 'Tuzlukçu'),
(651, 'Konya', 'Yalıhüyük'),
(652, 'Kütahya', 'Altıntaş'),
(653, 'Kütahya', 'Domaniç'),
(654, 'Kütahya', 'Emet'),
(655, 'Kütahya', 'Gediz'),
(656, 'Kütahya', 'Kütahya Merkez'),
(657, 'Kütahya', 'Simav'),
(658, 'Kütahya', 'Tavşanlı'),
(659, 'Kütahya', 'Aslanapa'),
(660, 'Kütahya', 'Dumlupınar'),
(661, 'Kütahya', 'Hisarcık'),
(662, 'Kütahya', 'Şaphane'),
(663, 'Kütahya', 'Çavdarhisar'),
(664, 'Kütahya', 'Pazarlar'),
(665, 'Malatya', 'Akçadağ'),
(666, 'Malatya', 'Arapgir'),
(667, 'Malatya', 'Arguvan'),
(668, 'Malatya', 'Darende'),
(669, 'Malatya', 'Doğanşehir'),
(670, 'Malatya', 'Hekimhan'),
(671, 'Malatya', 'Pütürge'),
(672, 'Malatya', 'Yeşilyurt / Malatya'),
(673, 'Malatya', 'Battalgazi'),
(674, 'Malatya', 'Doğanyol'),
(675, 'Malatya', 'Kale / Malatya'),
(676, 'Malatya', 'Kuluncak'),
(677, 'Malatya', 'Yazıhan'),
(678, 'Manisa', 'Akhisar'),
(679, 'Manisa', 'Alaşehir'),
(680, 'Manisa', 'Demirci'),
(681, 'Manisa', 'Gördes'),
(682, 'Manisa', 'Kırkağaç'),
(683, 'Manisa', 'Kula'),
(684, 'Manisa', 'Salihli'),
(685, 'Manisa', 'Sarıgöl'),
(686, 'Manisa', 'Saruhanlı'),
(687, 'Manisa', 'Selendi'),
(688, 'Manisa', 'Soma'),
(689, 'Manisa', 'Turgutlu'),
(690, 'Manisa', 'Ahmetli'),
(691, 'Manisa', 'Gölmarmara'),
(692, 'Manisa', 'Köprübaşı / Manisa'),
(693, 'Manisa', 'Şehzadeler'),
(694, 'Manisa', 'Yunusemre'),
(695, 'Mardin', 'Derik'),
(696, 'Mardin', 'Kızıltepe'),
(697, 'Mardin', 'Mazıdağı'),
(698, 'Mardin', 'Midyat'),
(699, 'Mardin', 'Nusaybin'),
(700, 'Mardin', 'Ömerli'),
(701, 'Mardin', 'Savur'),
(702, 'Mardin', 'Dargeçit'),
(703, 'Mardin', 'Yeşilli'),
(704, 'Mardin', 'Artuklu'),
(705, 'Mersin', 'Anamur'),
(706, 'Mersin', 'Erdemli'),
(707, 'Mersin', 'Gülnar'),
(708, 'Mersin', 'Mut'),
(709, 'Mersin', 'Silifke'),
(710, 'Mersin', 'Tarsus'),
(711, 'Mersin', 'Aydıncık / Mersin'),
(712, 'Mersin', 'Bozyazı'),
(713, 'Mersin', 'Çamlıyayla'),
(714, 'Mersin', 'Akdeniz'),
(715, 'Mersin', 'Mezitli'),
(716, 'Mersin', 'Toroslar'),
(717, 'Mersin', 'Yenişehir / Mersin'),
(718, 'Muğla', 'Bodrum'),
(719, 'Muğla', 'Datça'),
(720, 'Muğla', 'Fethiye'),
(721, 'Muğla', 'Köyceğiz'),
(722, 'Muğla', 'Marmaris'),
(723, 'Muğla', 'Milas'),
(724, 'Muğla', 'Ula'),
(725, 'Muğla', 'Yatağan'),
(726, 'Muğla', 'Dalaman'),
(727, 'Muğla', 'Ortaca'),
(728, 'Muğla', 'Kavaklıdere'),
(729, 'Muğla', 'Menteşe'),
(730, 'Muğla', 'Seydikemer'),
(731, 'Muş', 'Bulanık'),
(732, 'Muş', 'Malazgirt'),
(733, 'Muş', 'Muş Merkez'),
(734, 'Muş', 'Varto'),
(735, 'Muş', 'Hasköy'),
(736, 'Muş', 'Korkut'),
(737, 'Nevşehir', 'Avanos'),
(738, 'Nevşehir', 'Derinkuyu'),
(739, 'Nevşehir', 'Gülşehir'),
(740, 'Nevşehir', 'Hacıbektaş'),
(741, 'Nevşehir', 'Kozaklı'),
(742, 'Nevşehir', 'Nevşehir Merkez'),
(743, 'Nevşehir', 'Ürgüp'),
(744, 'Nevşehir', 'Acıgöl'),
(745, 'Niğde', 'Bor'),
(746, 'Niğde', 'Çamardı'),
(747, 'Niğde', 'Niğde Merkez'),
(748, 'Niğde', 'Ulukışla'),
(749, 'Niğde', 'Altunhisar'),
(750, 'Niğde', 'Çiftlik'),
(751, 'Ordu', 'Akkuş'),
(752, 'Ordu', 'Aybastı'),
(753, 'Ordu', 'Fatsa'),
(754, 'Ordu', 'Gölköy'),
(755, 'Ordu', 'Korgan'),
(756, 'Ordu', 'Kumru'),
(757, 'Ordu', 'Mesudiye'),
(758, 'Ordu', 'Perşembe'),
(759, 'Ordu', 'Ulubey / Ordu'),
(760, 'Ordu', 'Ünye'),
(761, 'Ordu', 'Gülyalı'),
(762, 'Ordu', 'Gürgentepe'),
(763, 'Ordu', 'Çamaş'),
(764, 'Ordu', 'Çatalpınar'),
(765, 'Ordu', 'Çaybaşı'),
(766, 'Ordu', 'İkizce'),
(767, 'Ordu', 'Kabadüz'),
(768, 'Ordu', 'Kabataş'),
(769, 'Ordu', 'Altınordu'),
(770, 'Osmaniye', 'Bahçe'),
(771, 'Osmaniye', 'Kadirli'),
(772, 'Osmaniye', 'Osmaniye Merkez'),
(773, 'Osmaniye', 'Düziçi'),
(774, 'Osmaniye', 'Hasanbeyli'),
(775, 'Osmaniye', 'Sumbas'),
(776, 'Osmaniye', 'Toprakkale'),
(777, 'Rize', 'Ardeşen'),
(778, 'Rize', 'Çamlıhemşin'),
(779, 'Rize', 'Çayeli'),
(780, 'Rize', 'Fındıklı'),
(781, 'Rize', 'İkizdere'),
(782, 'Rize', 'Kalkandere'),
(783, 'Rize', 'Pazar / Rize'),
(784, 'Rize', 'Rize Merkez'),
(785, 'Rize', 'Güneysu'),
(786, 'Rize', 'Derepazarı'),
(787, 'Rize', 'Hemşin'),
(788, 'Rize', 'İyidere'),
(789, 'Sakarya', 'Akyazı'),
(790, 'Sakarya', 'Geyve'),
(791, 'Sakarya', 'Hendek'),
(792, 'Sakarya', 'Karasu'),
(793, 'Sakarya', 'Kaynarca'),
(794, 'Sakarya', 'Sapanca'),
(795, 'Sakarya', 'Kocaali'),
(796, 'Sakarya', 'Pamukova'),
(797, 'Sakarya', 'Taraklı'),
(798, 'Sakarya', 'Ferizli'),
(799, 'Sakarya', 'Karapürçek'),
(800, 'Sakarya', 'Söğütlü'),
(801, 'Sakarya', 'Adapazarı'),
(802, 'Sakarya', 'Arifiye'),
(803, 'Sakarya', 'Erenler'),
(804, 'Sakarya', 'Serdivan'),
(805, 'Samsun', 'Alaçam'),
(806, 'Samsun', 'Bafra'),
(807, 'Samsun', 'Çarşamba'),
(808, 'Samsun', 'Havza'),
(809, 'Samsun', 'Kavak'),
(810, 'Samsun', 'Ladik'),
(811, 'Samsun', 'Terme'),
(812, 'Samsun', 'Vezirköprü'),
(813, 'Samsun', 'Asarcık'),
(814, 'Samsun', '19 Mayıs'),
(815, 'Samsun', 'Salıpazarı'),
(816, 'Samsun', 'Tekkeköy'),
(817, 'Samsun', 'Ayvacık / Samsun'),
(818, 'Samsun', 'Yakakent'),
(819, 'Samsun', 'Atakum'),
(820, 'Samsun', 'Canik'),
(821, 'Samsun', 'İlkadım'),
(822, 'Siirt', 'Baykan'),
(823, 'Siirt', 'Eruh'),
(824, 'Siirt', 'Kurtalan'),
(825, 'Siirt', 'Pervari'),
(826, 'Siirt', 'Siirt Merkez'),
(827, 'Siirt', 'Şirvan'),
(828, 'Siirt', 'Tillo'),
(829, 'Sinop', 'Ayancık'),
(830, 'Sinop', 'Boyabat'),
(831, 'Sinop', 'Durağan'),
(832, 'Sinop', 'Erfelek'),
(833, 'Sinop', 'Gerze'),
(834, 'Sinop', 'Sinop Merkez'),
(835, 'Sinop', 'Türkeli'),
(836, 'Sinop', 'Dikmen'),
(837, 'Sinop', 'Saraydüzü'),
(838, 'Sivas', 'Divriği'),
(839, 'Sivas', 'Gemerek'),
(840, 'Sivas', 'Gürün'),
(841, 'Sivas', 'Hafik'),
(842, 'Sivas', 'İmranlı'),
(843, 'Sivas', 'Kangal'),
(844, 'Sivas', 'Koyulhisar'),
(845, 'Sivas', 'Sivas Merkez'),
(846, 'Sivas', 'Suşehri'),
(847, 'Sivas', 'Şarkışla'),
(848, 'Sivas', 'Yıldızeli'),
(849, 'Sivas', 'Zara'),
(850, 'Sivas', 'Akıncılar'),
(851, 'Sivas', 'Altınyayla / Sivas'),
(852, 'Sivas', 'Doğanşar'),
(853, 'Sivas', 'Gölova'),
(854, 'Sivas', 'Ulaş'),
(855, 'Şanlıurfa', 'Akçakale'),
(856, 'Şanlıurfa', 'Birecik'),
(857, 'Şanlıurfa', 'Bozova'),
(858, 'Şanlıurfa', 'Ceylanpınar'),
(859, 'Şanlıurfa', 'Halfeti'),
(860, 'Şanlıurfa', 'Hilvan'),
(861, 'Şanlıurfa', 'Siverek'),
(862, 'Şanlıurfa', 'Suruç'),
(863, 'Şanlıurfa', 'Viranşehir'),
(864, 'Şanlıurfa', 'Harran'),
(865, 'Şanlıurfa', 'Eyyübiye'),
(866, 'Şanlıurfa', 'Haliliye'),
(867, 'Şanlıurfa', 'Karaköprü'),
(868, 'Şırnak', 'Beytüşşebap'),
(869, 'Şırnak', 'Cizre'),
(870, 'Şırnak', 'İdil'),
(871, 'Şırnak', 'Silopi'),
(872, 'Şırnak', 'Şırnak Merkez'),
(873, 'Şırnak', 'Uludere'),
(874, 'Şırnak', 'Güçlükonak'),
(875, 'Tekirdağ', 'Çerkezköy'),
(876, 'Tekirdağ', 'Çorlu'),
(877, 'Tekirdağ', 'Hayrabolu'),
(878, 'Tekirdağ', 'Malkara'),
(879, 'Tekirdağ', 'Muratlı'),
(880, 'Tekirdağ', 'Saray / Tekirdağ'),
(881, 'Tekirdağ', 'Şarköy'),
(882, 'Tekirdağ', 'Marmaraereğlisi'),
(883, 'Tekirdağ', 'Ergene'),
(884, 'Tekirdağ', 'Süleymanpaşa'),
(885, 'Tokat', 'Almus'),
(886, 'Tokat', 'Artova'),
(887, 'Tokat', 'Erbaa'),
(888, 'Tokat', 'Niksar'),
(889, 'Tokat', 'Reşadiye'),
(890, 'Tokat', 'Tokat Merkez'),
(891, 'Tokat', 'Turhal'),
(892, 'Tokat', 'Zile'),
(893, 'Tokat', 'Pazar / Tokat'),
(894, 'Tokat', 'Yeşilyurt / Tokat'),
(895, 'Tokat', 'Başçiftlik'),
(896, 'Tokat', 'Sulusaray'),
(897, 'Trabzon', 'Akçaabat'),
(898, 'Trabzon', 'Araklı'),
(899, 'Trabzon', 'Arsin'),
(900, 'Trabzon', 'Çaykara'),
(901, 'Trabzon', 'Maçka'),
(902, 'Trabzon', 'Of'),
(903, 'Trabzon', 'Sürmene'),
(904, 'Trabzon', 'Tonya'),
(905, 'Trabzon', 'Vakfıkebir'),
(906, 'Trabzon', 'Yomra'),
(907, 'Trabzon', 'Beşikdüzü'),
(908, 'Trabzon', 'Şalpazarı'),
(909, 'Trabzon', 'Çarşıbaşı'),
(910, 'Trabzon', 'Dernekpazarı'),
(911, 'Trabzon', 'Düzköy'),
(912, 'Trabzon', 'Hayrat'),
(913, 'Trabzon', 'Köprübaşı / Trabzon'),
(914, 'Trabzon', 'Ortahisar'),
(915, 'Tunceli', 'Çemişgezek'),
(916, 'Tunceli', 'Hozat'),
(917, 'Tunceli', 'Mazgirt'),
(918, 'Tunceli', 'Nazımiye'),
(919, 'Tunceli', 'Ovacık / Tunceli'),
(920, 'Tunceli', 'Pertek'),
(921, 'Tunceli', 'Pülümür'),
(922, 'Tunceli', 'Tunceli Merkez'),
(923, 'Uşak', 'Banaz'),
(924, 'Uşak', 'Eşme'),
(925, 'Uşak', 'Karahallı'),
(926, 'Uşak', 'Sivaslı'),
(927, 'Uşak', 'Ulubey / Uşak'),
(928, 'Uşak', 'Uşak Merkez'),
(929, 'Van', 'Başkale'),
(930, 'Van', 'Çatak'),
(931, 'Van', 'Erciş'),
(932, 'Van', 'Gevaş'),
(933, 'Van', 'Gürpınar'),
(934, 'Van', 'Muradiye'),
(935, 'Van', 'Özalp'),
(936, 'Van', 'Bahçesaray'),
(937, 'Van', 'Çaldıran'),
(938, 'Van', 'Edremit / Van'),
(939, 'Van', 'Saray / Van'),
(940, 'Van', 'İpekyolu'),
(941, 'Van', 'Tuşba'),
(942, 'Yalova', 'Yalova Merkez'),
(943, 'Yalova', 'Altınova'),
(944, 'Yalova', 'Armutlu'),
(945, 'Yalova', 'Çınarcık'),
(946, 'Yalova', 'Çiftlikköy'),
(947, 'Yalova', 'Termal'),
(948, 'Yozgat', 'Akdağmadeni'),
(949, 'Yozgat', 'Boğazlıyan'),
(950, 'Yozgat', 'Çayıralan'),
(951, 'Yozgat', 'Çekerek'),
(952, 'Yozgat', 'Sarıkaya'),
(953, 'Yozgat', 'Sorgun'),
(954, 'Yozgat', 'Şefaatli'),
(955, 'Yozgat', 'Yerköy'),
(956, 'Yozgat', 'Yozgat Merkez'),
(957, 'Yozgat', 'Aydıncık / Yozgat'),
(958, 'Yozgat', 'Çandır'),
(959, 'Yozgat', 'Kadışehri'),
(960, 'Yozgat', 'Saraykent'),
(961, 'Yozgat', 'Yenifakılı'),
(962, 'Zonguldak', 'Çaycuma'),
(963, 'Zonguldak', 'Devrek'),
(964, 'Zonguldak', 'Ereğli / Zonguldak'),
(965, 'Zonguldak', 'Zonguldak Merkez'),
(966, 'Zonguldak', 'Alaplı'),
(967, 'Zonguldak', 'Gökçebey');";

		require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
		dbDelta($sql);
	}

	
 
}



function ss_earthquake_form_uninstall() {
	global $wpdb;
  	$table_name = $wpdb->prefix . 'ss_earthquake_form';
  	$table_name2 = $wpdb->prefix . 'ss_province';

  	if($wpdb->get_var("show tables like '$table_name'") == $table_name) 
	{
		$sql = "DROP TABLE IF EXISTS $table_name;";
 		$wpdb->query($sql);
	}
	if($wpdb->get_var("show tables like '$table_name2'") == $table_name2) 
	{
		$sql = "DROP TABLE IF EXISTS $table_name2;";
		$wpdb->query($sql);
	}
}

/*// run the install scripts upon plugin activation
register_activation_hook(__FILE__,'ss_earthquake_form_install');
register_deactivation_hook(__FILE__, 'ss_earthquake_form_uninstall'); 
register_uninstall_hook(__FILE__, 'ss_earthquake_form_uninstall' );
*/

?>